package com.pend.interfaces;

public interface IApiEvent {
    int REQUEST_LOGIN_CODE = 1;
    int REQUEST_SIGN_UP_CODE = 2;
    int REQUEST_UPDATE_USER_PROFILE_CODE = 3;
    int REQUEST_GET_USER_PROFILE_CODE = 4;
    int REQUEST_UPDATE_USER_SEETING_CODE = 5;
    int REQUEST_USER_LOGOUT_CODE = 6;
    int REQUEST_USER_ONLINE_CODE = 7;
    int REQUEST_FORGOT_PASSWORD_CODE = 8;
    int REQUEST_ADD_USER_IMAGE_CODE = 9;
    int REQUEST_DELETE_USER_IMAGE_CODE = 10;
    int REQUEST_SET_USER_IMAGE_CODE = 11;
    int REQUEST_GET_USER_TIME_SHEET_CODE = 12;

}
